fix harcoded

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -24,8 +24,8 @@ jobs:
 
       - name: Check if docs version already exist
         run: |
-          ls versioned_sidebars | grep "version-2.2-sidebars.json" ;
-          if [ $? -eq 0 ]; then echo "::error:: Version already exist" >> $GITHUB_OUTPUT && exit 1; fi
+          ls versioned_sidebars | grep "version-${{ github.event.inputs.version }}-sidebars.json" ;
+          if [ $? -eq 0 ]; then echo "::error:: Version already exist" && exit 1; fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v3.7.0
